### ISSUE TITLE
`content` is not defined in `Quote.js`

### ISSUE THREAD

**Issue by zalmoxisus** [grommet/grommet-presentation#1]
[Quote.js#L25](https://github.com/grommet/grommet-presentation/blob/master/src/js/components/Quote.js#L25)

**Comment by alansouzati** [comment]
This is me doing wrong stuff hahaha. This has to be removed entirely. Would you be willing to send a PR? Or do you prefer myself to remove it?

**Comment by zalmoxisus** [comment]
@alansouzati, surely, no problems :)
